### ISSUE TITLE
Confusing documentation

### ISSUE THREAD

**Issue by trourance** [kabirbaidhya/pglistend#11]
Hi,
I've tried the tutorial, but documentation provided is wrong. If you edit the file `/etc/pglistend/config.yml` and put all the configuration in it as described, you get the following error:

`Error: No database connections are configured. Please do configure properly and start pglistend again.`

You have to put the following minimum syntax in the file `/etc/pglistend/config.yml` :

```python
default:

# Include configuration files database connections you want to use
connections:
    - /etc/pglistend/pglistend-connection.yml
```
And then put all the configuration provided in `/etc/pglistend/pglistend-connection.yml`.

It is really confusing and I don't understand the purpose of those two files, particulary the default section.

**Comment by kabirbaidhya** [comment]
Hi @fluancefg ,
Actually, the documentation is a bit outdated. It still reflects what we initially had in the configuration. I forgot to update the docs. My apologies for that :). 

The main config file is `/etc/pglistend/config.yml`. There are two keys `default` and `connections`:

### connections
Here in the new config format you will need to provide a list of connection config files to load from, in the `connections` array. Actually we made this change as we required to support multiple database for multiple projects. So, these are just the yml files each containing database config for each of the database you'd want the service to listen to. 

Each of the connection `yml` files you list under this `connections` array follows this format: https://github.com/kabirbaidhya/pglistend/blob/master/.pglistend-connection.yml.dist
```
# database connection
connection:
    database: DATABASE_NAME
    user: YOUR_USERNAME
    password: PASSWORD
    port: 5432
    max: 2

# channels to LISTEN to
channels: [CHANNEL_1, CHANNEL_2]

# list of listener scripts to be included
scripts:
    - /path/to/listener/script.js
#    - path/to/another/listener-script.js
```
I think the listener script issue(https://github.com/kabirbaidhya/pglistend/issues/10) you've posted is because of this as well. 

### default
You can set default values to be used for each of the database connection under this `default` key. The format is same as the connection config values. Just that if you don't specify some values in your database connection config it would take these default values. 

For instance: 
If you put these under `default` you can just skip these keys in your database configuration file. But if you put these keys they'd override the default ones. 
```
default:
    connection:
        host: localhost
        port: 5432
        max: 2
        idleTimeoutMillis: 10000
```

**Comment by kabirbaidhya** [comment]
Here's a sample config:

**/etc/pglistend/config.yml**
```
default:
    connection:
        host: localhost
        port: 5432
        max: 2
        idleTimeoutMillis: 10000

connections:
    - /source/test-project/pglistend-db.yml
    - /source/test-project2/pglistend-db.yml
```
**/source/test-project/pglistend-db.yml**

```
# postgresql connection
connection:
    user: 'test_project'
    database: 'test_project'
    password: 'test'
    port: 5444
    max: 10

# channels to LISTEN to
channels:
    - update
    - insert
    - delete
    - news_update
    - foo
```
